### ISSUE TITLE
Should mark lazy values as @transient(?)

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis-contrib#82] opened 2019-01-07 16:21 UTC
Caching a `GeotiffRasterSource` causes NPE when the lazy vals are accessed a second time (unless the val is called and laziness is voided prior to caching). Marking lazy vals as transient might prevent this issue

**Comment by moradology** [comment] 2019-06-13 16:22
For example, [these lazy vals](https://github.com/geotrellis/geotrellis-contrib/blob/e6c3696638834a1d987be246d3d76748c0ff5a7a/gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALRasterSource.scala#L58-L69) are set to `null` upon deserializing them from a cache

**Comment by pomadchin** [comment] 2019-07-17 14:45
It looks like the issue was related to the common GDAL bindings and to its usage in our previous version of this API. At this point it seems to me that [we're not pre-caching in RF](https://github.com/raster-foundry/raster-foundry/blob/a9aed578fa55372ecdea47023beee4ba450a08ef/app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala) anymore. @moradology can correct me or add some more details to my comments and it looks like this issue can be closed and marked as resolved.

**Comment by echeipesh** [comment] 2019-07-25 16:20
Closing this as "could not reproduce" maybe it just got solved by changes along the way.

**Closed by echeipesh** 2019-07-25 16:20 UTC
Labels: bug
